---
to: <%= path %>/<%= name %>.stories.tsx
---
/** auto-generated by hygen-stories */
<% if (styles !== 'null') { %>
import './<%= styles %>';
<% } %>
import { ComponentMeta, ComponentStory } from '@storybook/react';

import {<%= name %>} from './<%= fileName %>';

export default {
    title: '<%= name %>',
    component: <%= name %>,
} as ComponentMeta<typeof <%= name %>>;

const Template: ComponentStory<typeof  <%= name %>> = (args) => {
  return <<%= name %> {...args} />
};

export const Default = Template.bind({});

